export const styles = {
  appShell: { fontFamily: "'Inter', sans-serif", minHeight: "100vh" },
  centerScreen: { minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--ink)" },
  sidebar: { width: 240, minHeight: "100vh", background: "var(--ink-2)", display: "flex", flexDirection: "column", borderRight: "1px solid rgba(196,151,90,0.12)" },
  navItem: { display: "flex", alignItems: "center", gap: 10, width: "100%", padding: "10px 12px", background: "transparent", border: "none", borderRadius: 6, fontSize: 13.5, cursor: "pointer", marginBottom: 2, textAlign: "left" },
  logoutBtn: { display: "flex", alignItems: "center", gap: 8, width: "100%", padding: "9px 12px", background: "transparent", border: "1px solid rgba(120,112,96,0.25)", borderRadius: 6, color: "var(--slate)", fontSize: 13, cursor: "pointer" },
  panel: { background: "var(--ink-2)", border: "1px solid rgba(196,151,90,0.15)", borderRadius: 12, padding: 24 },
  input: { width: "100%", padding: "10px 12px", background: "rgba(240,244,248,0.04)", border: "1px solid rgba(120,112,96,0.3)", borderRadius: 7, color: "var(--paper)", fontSize: 14 },
  primaryBtn: { display: "flex", alignItems: "center", justifyContent: "center", gap: 6, width: "100%", padding: "11px 16px", background: "var(--gold)", border: "none", borderRadius: 7, color: "var(--ink)", fontWeight: 600, fontSize: 14, cursor: "pointer" },
  primaryBtnSm: { display: "flex", alignItems: "center", gap: 6, padding: "8px 14px", background: "var(--gold)", border: "none", borderRadius: 7, color: "var(--ink)", fontWeight: 600, fontSize: 13, cursor: "pointer", whiteSpace: "nowrap" },
  secondaryBtn: { display: "flex", alignItems: "center", gap: 8, padding: "10px 16px", background: "transparent", border: "1px solid var(--gold)", borderRadius: 7, color: "var(--gold)", fontSize: 13.5, cursor: "pointer" },
  ghostBtnSm: { padding: "6px 12px", background: "transparent", border: "1px solid rgba(120,112,96,0.3)", borderRadius: 6, color: "var(--slate)", fontSize: 12.5, cursor: "pointer" },
  dangerBtnSm: { padding: "6px 12px", background: "var(--red)", border: "none", borderRadius: 6, color: "#2b0b0b", fontSize: 12.5, fontWeight: 600, cursor: "pointer" },
  dangerLinkBtn: { display: "flex", alignItems: "center", gap: 6, background: "transparent", border: "none", color: "var(--red)", fontSize: 12.5, cursor: "pointer", padding: 0 },
  clientCard: { textAlign: "left", background: "var(--ink-2)", border: "1px solid rgba(196,151,90,0.15)", borderRadius: 12, padding: 18, cursor: "pointer" },
  tabRow: { display: "flex", gap: 4, marginTop: 24, borderBottom: "1px solid rgba(120,112,96,0.15)" },
  tabBtn: { padding: "10px 14px", background: "transparent", border: "none", borderBottom: "2px solid transparent", color: "var(--slate)", fontSize: 13.5, cursor: "pointer" },
  tabBtnActive: { color: "var(--gold)", borderBottom: "2px solid var(--gold)" },
  backBtn: { background: "transparent", border: "none", color: "var(--slate)", fontSize: 13, cursor: "pointer", padding: 0, marginBottom: 10 },
  fileRow: { display: "flex", alignItems: "center", gap: 12, padding: "12px 14px", background: "rgba(240,244,248,0.03)", border: "1px solid rgba(120,112,96,0.15)", borderRadius: 9 },
  iconBtn: { display: "flex", alignItems: "center", justifyContent: "center", width: 30, height: 30, background: "transparent", border: "1px solid rgba(120,112,96,0.25)", borderRadius: 6, color: "var(--slate)", cursor: "pointer", textDecoration: "none" },
  pill: { display: "flex", alignItems: "center", gap: 5, padding: "5px 10px", borderRadius: 999, border: "1px solid", fontSize: 12, fontWeight: 500, background: "none" },
  chip: { padding: "6px 12px", borderRadius: 999, border: "1px solid rgba(120,112,96,0.3)", background: "transparent", color: "var(--slate)", fontSize: 12.5, cursor: "pointer" },
  chipActive: { border: "1px solid var(--gold)", color: "var(--gold)", background: "rgba(196,151,90,0.08)" },
  dropzone: { border: "1.5px dashed rgba(196,151,90,0.3)", borderRadius: 12, padding: "32px 16px", textAlign: "center", cursor: "pointer" },
  inlineForm: { display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(11,37,69,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50, padding: 16 },
  modal: { width: "100%", maxWidth: 420, background: "var(--ink-2)", border: "1px solid rgba(196,151,90,0.2)", borderRadius: 14, padding: 24 },
};
